---
apiVersion: v1
kind: Namespace
metadata:
  name: gocd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gocd-agent
  namespace: gocd
  labels:
    name: gocd-agent
    version: 16.12.0
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: gocd-agent
    spec:
      containers:
      - name: gocd-agent
        image: gocd/gocd-agent:16.12.0
        env:
        - name: GO_SERVER
          value: gocd-server